### ISSUE TITLE
addition of architectural elements in your add-on configurable ? (Issue #49) - 3 examples (Issue #50)

### ISSUE THREAD

**Issue by boes3d** [brunopostle/homemaker-addon#51] opened 2022-10-19 05:58 UTC
Hello Mr Postle
Would it be possible to configure the styles myself in your addon?
(data access for this modification should be given to the user?)
Do you have an example of configuration and style implementation ("Fancy" by example) in your addon homemaker?
Thank you in advance for your answer.
Best regards.
M Rémy HAENEL

**Comment by brunopostle** [comment] 2022-10-19 21:55
The styles are defined as files in folders within the 'share' folder.

I am in the process of changing all the assets for the next release. In the current release, all the windows, doors, columns etc... are defined as 3D DXF files, you can [download them here](https://github.com/brunopostle/homemaker-addon/tree/main/molior/style/share)

These DXF files are not very BIM friendly, so the next release will be based on my work in the '[ifcassets](https://github.com/brunopostle/homemaker-addon/tree/ifcassets)' branch. In this branch all the assets are IFC types in a library file, there is one file for each style: [library.ifc](https://github.com/brunopostle/homemaker-addon/blob/ifcassets/molior/style/share/library.ifc), [fancy/library.ifc](https://github.com/brunopostle/homemaker-addon/blob/ifcassets/molior/style/share/fancy/library.ifc), [halifax/tuscan/library.ifc](https://github.com/brunopostle/homemaker-addon/blob/ifcassets/molior/style/share/halifax/tuscan/library.ifc), etc..

The advantage of putting the assets in an IFC library is that they can be edited in blenderbim, where they can have property sets, predefinedtypes, multiple materials, multiple representations and all the other nice things that BIM types can have.

**Comment by brunopostle** [comment] 2022-12-30 10:48
Duplicate of #49

**Closed** 2022-12-30 10:48 UTC
