### ISSUE TITLE
It cannot be installed successfully

### ISSUE THREAD

**Issue by justinjow** [brunopostle/homemaker-addon#44] opened 2022-04-29 03:36 UTC
I really love this addon，however it cannot be installed successfully on Macbook Pro 14 with M1 MAX. The BlenderBIM Add-on with the tag "py310" cannot be installed successfully too.

**Comment by brunopostle** [comment] 2022-04-29 08:13
We don't own an M1 apple silicon computer that can compile the Topologic library. Blenderbim has the same problem: IfcOpenShell/IfcOpenShell#2090

Apparently, it is possible to run Blenderbim under emulation, you would need to install the 'Intel' version of Blender (not the 'Apple Silicon' version), then possibly you can install Blenderbim and the Homemaker add-on.

Please write a comment here if this works, or if it doesn't work.

**Comment by dirkolbrich** [comment] 2022-05-16 08:36
This indeed does work. Downloaded the Intel version from Blender.org, installed (kept both Blender versions, renamed one to `Blender Intel`), then installed the BlenderBIM Add-on -> success. Both blender versions even share the same Preferences as far as I can tell.

**Comment by brunopostle** [comment] 2022-12-30 10:52
Duplicate of #1

**Closed by brunopostle** 2022-12-30 10:52 UTC
