### ISSUE TITLE
addition of architectural elements in your add-on configurable ? (Issue #49) - 3 examples

### ISSUE THREAD

**Issue by boes3d** [brunopostle/homemaker-addon#50] opened 2022-10-17 08:13 UTC
Hi M POSTLE,
You will find attached 3 examples of classic Parisian architecture built before the French Revolution of 1789.
Hoping this can help you.
Best regards
M Remy HAENEL

![exemple 1 - Hotel de SOUBISE - PARIS](https://user-images.githubusercontent.com/73269596/196122906-a739bcad-3335-4062-91a6-c822d58087b2.jpg)
![exemple 2 - Maison MASSERANO - PARIS](https://user-images.githubusercontent.com/73269596/196122908-d2100269-0f2b-4d81-949c-a7252c13495c.jpg)
![exemple 3 - Maison de Mme GOUTEAU - PARIS](https://user-images.githubusercontent.com/73269596/196122909-bd8edd45-82c1-4458-811b-a37366e99ac9.jpg)

**Comment by brunopostle** [comment] 2022-10-18 21:33
Thanks they are very elegant, I wish I had time to spend days modelling all these details for use in Homemaker :(

**Comment by brunopostle** [comment] 2022-12-30 10:50
Duplicate of #49

**Closed by brunopostle** 2022-12-30 10:50 UTC
